name = "remesillo"
main = "dist/index.js"
compatibility_date = "2025-10-12"

[build]
command = "tsc"

[build.upload]
format = "modules"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.